sudo: false
dist: trusty
language: php
php: '7.2'
services: docker
before_install:
  - composer global require 'hirak/prestissimo:^0.3'
script:
  - set -e
  - ./build/composer.sh
  - vendor/bin/phpunit
  - ./build/build.sh