version: '3.4'
services:
  app:
    build: ./docker/php
    volumes:
      - .:/var/code
    links:
      - db
  db:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=unitest"
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=test"
      - "MYSQL_ROOT_PASSWORD=test"
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:4-alpine
    ports:
      - "6379:6379"
volumes:
  dbdata: