version: '3.4'
services:
  web:
    image: nginx:1.13-alpine
    volumes:
      - ./docker/nginx/aws.conf:/etc/nginx/conf.d/default.conf
      - .:/var/code
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/code
    links:
      - db
  db:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=unitest"
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=test"
      - "MYSQL_ROOT_PASSWORD=test"
    ports:
      - "3306:3306"
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: redis:4-alpine
    ports:
      - "6379:6379"
volumes:
  dbdata: